"""two columns added

Revision ID: 946bb8aaaf39
Revises: 2fa52721b06f
Create Date: 2024-01-29 17:01:41.095673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946bb8aaaf39'
down_revision = '2fa52721b06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
